export const BookData =[
    {
        id: 0,
        book_name: "Harry Potter and the Philosofher's Stone",
        book_url: "https://m.media-amazon.com/images/I/5165He67NEL._SY346_.jpg",
        book_description: "Harry Potter and the Philosopher's Stone follows the magical journey of a young wizard discovering his identity, friendships, and facing a dark mystery at Hogwarts School of Witchcraft and Wizardry.",
        print_length: "345 pages",
        language: "English",
        author_name: "J.K.Rowling",
        price:"305",
    },

    {
        id: 1,
        book_name: "The jungle Book",
        book_url: "https://m.media-amazon.com/images/I/51cCdjGzuVL._BO1,204,203,200_.jpg",
        book_description: "The Jungle Book by  Rudyard Kipling is a classic collection of stories that follows the adventures of Mowgli, a young boy raised by wolves in the Indian jungle, as he encounters various animals and learns the laws of the wild.",
        print_length: "200 pages",
        language: "English",
        author_name: "Rudyard Kipling",
        price:"340",
    },

    {
        id: 2,
        book_name: "Treasure Island",
        book_url: "https://m.media-amazon.com/images/I/710K9pWWZ+L._SL1400_.jpg",
        book_description: "Treasure Island is an adventurous tale of pirates, buried treasure, and swashbuckling escapades, as young Jim Hawkins embarks on a perilous journey to uncover the secrets of a pirate's map.",
        print_length: "236 pages",
        language: "English",
        author_name: "R.L.Stevenson",
        price:"108",
    },

    {
        id: 3,
        book_name: "From the earth to the moon",
        book_url: "https://m.media-amazon.com/images/I/81q-OtlhktL._SL1200_.jpg",
        book_description: "From the Earth to the Moon by Jules Verne is a classic science fiction novel that follows the ambitious plan of the Baltimore Gun Club to launch a projectile to the moon using a massive cannon.",
        print_length: "240 pages",
        language: "English",
        author_name: "Jules Verne",
        price:"202",
    },

    {
        id: 4,
        book_name: "Harry Potter and the Philosofher's Stone",
        book_url: "https://m.media-amazon.com/images/I/5165He67NEL._SY346_.jpg",
        book_description: "dfgghgfv",
        print_length: "345 pages",
        language: "English",
        author_name: "J.K.Rowling",
        price:"305",
    },

    {
        id: 5,
        book_name: "Harry Potter and the Philosofher's Stone",
        book_url: "https://m.media-amazon.com/images/I/5165He67NEL._SY346_.jpg",
        book_description: "dfgghgfv",
        print_length: "345 pages",
        language: "English",
        author_name: "J.K.Rowling",
        price:"305",
    },

    {
        id: 6,
        book_name: "Harry Potter and the Philosofher's Stone",
        book_url: "https://m.media-amazon.com/images/I/5165He67NEL._SY346_.jpg",
        book_description: "dfgghgfv",
        print_length: "345 pages",
        language: "English",
        author_name: "J.K.Rowling",
        price:"305",
    },

    {
        id: 7,
        book_name: "Harry Potter and the Philosofher's Stone",
        book_url: "https://m.media-amazon.com/images/I/5165He67NEL._SY346_.jpg",
        book_description: "dfgghgfv",
        print_length: "345 pages",
        language: "English",
        author_name: "J.K.Rowling",
        price:"305",
    },

    {
        id: 8,
        book_name: "Harry Potter and the Philosofher's Stone",
        book_url: "https://m.media-amazon.com/images/I/5165He67NEL._SY346_.jpg",
        book_description: "dfgghgfv",
        print_length: "345 pages",
        language: "English",
        author_name: "J.K.Rowling",
        price:"305",
    },

    {
        id: 9,
        book_name: "Harry Potter and the Philosofher's Stone",
        book_url: "https://m.media-amazon.com/images/I/5165He67NEL._SY346_.jpg",
        book_description: "dfgghgfv",
        print_length: "345 pages",
        language: "English",
        author_name: "J.K.Rowling",
        price:"305",
    },

    {
        id: 10,
        book_name: "Harry Potter and the Philosofher's Stone",
        book_url: "https://m.media-amazon.com/images/I/5165He67NEL._SY346_.jpg",
        book_description: "dfgghgfv",
        print_length: "345 pages",
        language: "English",
        author_name: "J.K.Rowling",
        price:"305",
    },

    {
        id: 11,
        book_name: "Harry Potter and the Philosofher's Stone",
        book_url: "https://m.media-amazon.com/images/I/5165He67NEL._SY346_.jpg",
        book_description: "dfgghgfv",
        print_length: "345 pages",
        language: "English",
        author_name: "J.K.Rowling",
        price:"305",
    },

    {
        id: 12,
        book_name: "Harry Potter and the Philosofher's Stone",
        book_url: "https://m.media-amazon.com/images/I/5165He67NEL._SY346_.jpg",
        book_description: "dfgghgfv",
        print_length: "345 pages",
        language: "English",
        author_name: "J.K.Rowling",
        price:"305",
    },

    {
        id: 13,
        book_name: "Harry Potter and the Philosofher's Stone",
        book_url: "https://m.media-amazon.com/images/I/5165He67NEL._SY346_.jpg",
        book_description: "dfgghgfv",
        print_length: "345 pages",
        language: "English",
        author_name: "J.K.Rowling",
        price:"305",
    },

    {
        id: 14,
        book_name: "The Jungle Book",
        book_url: "https://m.media-amazon.com/images/I/5165He67NEL._SY346_.jpg",
        book_description: "dfgghgfv",
        print_length: "345 pages",
        language: "English",
        author_name: "J.K.Rowling",
        price:"305",
    },

    {
        id: 15,
        book_name: "Harry Potter and the Philosofher's Stone",
        book_url: "https://m.media-amazon.com/images/I/5165He67NEL._SY346_.jpg",
        book_description: "dfgghgfv",
        print_length: "345 pages",
        language: "English",
        author_name: "J.K.Rowling",
        price:"305",
    },

    {
        id: 16,
        book_name: "Harry Potter and the Philosofher's Stone",
        book_url: "https://m.media-amazon.com/images/I/5165He67NEL._SY346_.jpg",
        book_description: "dfgghgfv",
        print_length: "345 pages",
        language: "English",
        author_name: "J.K.Rowling",
        price:"305",
    },
]